version: "latest"

services:
  web:
    build: .

    command:
      - uvicorn
      - main:app
      - --host=0.0.0.0
      - --port=5430

    volumes:
      - .:/social_media

    ports:
      - 5430:5430

    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: